# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: randtest
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: quiztopia
# "service" is the name of this project. This will also be added to your AWS resource names.
service: quiztopia

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    QUIZ_TABLE: ${self:service}-quiz-two
    USER_TABLE: ${self:service}-user
    #LEADERBOARD_TABLE: ${self:service}-leaderboard
    TOKEN_SECRET: 09f26

  iam:
    role: arn:aws:iam::954976294667:role/whatisit-role

useDotenv: true

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true

functions:
  login:
    handler: functions/login/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: post
  signup:
    handler: functions/signup/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post
  postquiz:
    handler: functions/postquiz/postquiz.handler
    events:
      - httpApi:
          path: /quiz
          method: post

resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    quizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.QUIZ_TABLE}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
