# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: randtest
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: quiztopia
# "service" is the name of this project. This will also be added to your AWS resource names.
service: quiztopia

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    QUIZ_TABLE: ${self:service}-quiz
    USER_TABLE: ${self:service}-user
    #LEADERBOARD_TABLE: ${self:service}-leaderboard
    TOKEN_SECRET: 09f26
  iam:
    role:
      statements:
        - Effect: Allow
          - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.QUIZ_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_TABLE}
            #- arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.LEADERBOARD_TABLE}

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    quizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.QUIZ_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST


